title: Maxime Lasserre
baseURL: https://www.maximelasserre.com/
disableKinds:
  - taxonomy
  - term
defaultContentLanguage: fr
languages:
  fr:
    languageCode: fr
    contentDir: content/fr
    languageName: Français
    weight: 1
  en:
    languageCode: en
    contentDir: content/en
    languageName: English
    weight: 2
